compatibility_date = "2025-07-07"

# The name of the Cloudflare Pages service.
name = "example-counter-app"

# The bundle location for the Dioxus project, relative to this file.
pages_build_output_dir = "target/dx/example-counter-app/release/web/public"
